/* tslint:disable */
/* eslint-disable */
/**
 * P2P地震情報 API仕様書
 * - 商用・非商用問わず無償（無料）でご利用になれます。 [二次利用できます · P2P地震情報](https://www.p2pquake.net/secondary_use/) をご確認ください。 - 以下のレート制限があります。超えるとレスポンスが遅くなったり拒否 (HTTP ステータスコード 429) される場合があります。   - /history: 60 リクエスト/分 (IP アドレス毎)   - /jma: 10 リクエスト/分 (IP アドレス毎)
 *
 * The version of the OpenAPI document: 2.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "./runtime";
/**
 *
 * @export
 * @interface AreapeersAllOfAreas
 */
export interface AreapeersAllOfAreas {
  /**
   * 地域コード（コード一覧は [GitHub: epsp-specifications/epsp-area.csv · p2pquake/epsp-specifications](https://github.com/p2pquake/epsp-specifications/blob/master/epsp-area.csv) 参照）
   * @type {number}
   * @memberof AreapeersAllOfAreas
   */
  id: number;
  /**
   * ピア数
   * @type {number}
   * @memberof AreapeersAllOfAreas
   */
  peer: number;
}

/**
 * Check if a given object implements the AreapeersAllOfAreas interface.
 */
export function instanceOfAreapeersAllOfAreas(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "peer" in value;

  return isInstance;
}

export function AreapeersAllOfAreasFromJSON(json: any): AreapeersAllOfAreas {
  return AreapeersAllOfAreasFromJSONTyped(json, false);
}

export function AreapeersAllOfAreasFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AreapeersAllOfAreas {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    peer: json["peer"],
  };
}

export function AreapeersAllOfAreasToJSON(
  value?: AreapeersAllOfAreas | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    peer: value.peer,
  };
}
