/* tslint:disable */
/* eslint-disable */
/**
 * P2P地震情報 API仕様書
 * - 商用・非商用問わず無償（無料）でご利用になれます。 [二次利用できます · P2P地震情報](https://www.p2pquake.net/secondary_use/) をご確認ください。 - 以下のレート制限があります。超えるとレスポンスが遅くなったり拒否 (HTTP ステータスコード 429) される場合があります。   - /history: 60 リクエスト/分 (IP アドレス毎)   - /jma: 10 リクエスト/分 (IP アドレス毎)
 *
 * The version of the OpenAPI document: 2.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "./runtime";
import type { EEWAllOfAreas } from "./EEWAllOfAreas";
import {
  EEWAllOfAreasFromJSON,
  EEWAllOfAreasFromJSONTyped,
  EEWAllOfAreasToJSON,
} from "./EEWAllOfAreas";
import type { EEWAllOfEarthquake } from "./EEWAllOfEarthquake";
import {
  EEWAllOfEarthquakeFromJSON,
  EEWAllOfEarthquakeFromJSONTyped,
  EEWAllOfEarthquakeToJSON,
} from "./EEWAllOfEarthquake";
import type { EEWAllOfIssue } from "./EEWAllOfIssue";
import {
  EEWAllOfIssueFromJSON,
  EEWAllOfIssueFromJSONTyped,
  EEWAllOfIssueToJSON,
} from "./EEWAllOfIssue";

/**
 * 緊急地震速報（警報）の内容です。ただし、以下の点に留意してください。
 * - **内容や配信品質は無保証です。**緊急地震速報（警報）としての利活用は非推奨です。
 * - 多くの項目は[気象庁防災情報XMLフォーマット ｜ 技術資料](https://xml.kishou.go.jp/tec_material.html)の定義そのままです。地震の規模や予測震度なども提供しますが、緊急地震速報（警報）では発表されない内容です（参考：[気象庁｜緊急地震速報｜緊急地震速報（警報）及び（予報）について](https://www.data.jma.go.jp/svd/eew/data/nc/shikumi/shousai.html)）。
 * - スキーマは今後拡張する可能性があります。
 *
 * 遅延や欠落のリスクは以下の通りです。
 * - 処理遅延: WebSocket API は約 70ms 、 JSON API は約 1000 ms （高負荷時はさらに遅延します）
 * - サーバ所在地: 東京 (Linode Tokyo 2)
 * - 欠落リスク: サーバや受信プログラムは冗長化しておらず、障害時は配信できず、復旧時の再配信もありません
 * @export
 * @interface EEWAllOf
 */
export interface EEWAllOf {
  /**
   * 情報コード。常に556です。
   * @type {any}
   * @memberof EEWAllOf
   */
  code?: any | null;
  /**
   * テストかどうか。
   * @type {boolean}
   * @memberof EEWAllOf
   */
  test?: boolean;
  /**
   *
   * @type {EEWAllOfEarthquake}
   * @memberof EEWAllOf
   */
  earthquake?: EEWAllOfEarthquake;
  /**
   *
   * @type {EEWAllOfIssue}
   * @memberof EEWAllOf
   */
  issue: EEWAllOfIssue;
  /**
   * 取消
   * @type {boolean}
   * @memberof EEWAllOf
   */
  cancelled: boolean;
  /**
   * 細分区域
   * @type {Array<EEWAllOfAreas>}
   * @memberof EEWAllOf
   */
  areas?: Array<EEWAllOfAreas>;
}

/**
 * Check if a given object implements the EEWAllOf interface.
 */
export function instanceOfEEWAllOf(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "issue" in value;
  isInstance = isInstance && "cancelled" in value;

  return isInstance;
}

export function EEWAllOfFromJSON(json: any): EEWAllOf {
  return EEWAllOfFromJSONTyped(json, false);
}

export function EEWAllOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EEWAllOf {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    code: !exists(json, "code") ? undefined : json["code"],
    test: !exists(json, "test") ? undefined : json["test"],
    earthquake: !exists(json, "earthquake")
      ? undefined
      : EEWAllOfEarthquakeFromJSON(json["earthquake"]),
    issue: EEWAllOfIssueFromJSON(json["issue"]),
    cancelled: json["cancelled"],
    areas: !exists(json, "areas")
      ? undefined
      : (json["areas"] as Array<any>).map(EEWAllOfAreasFromJSON),
  };
}

export function EEWAllOfToJSON(value?: EEWAllOf | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    code: value.code,
    test: value.test,
    earthquake: EEWAllOfEarthquakeToJSON(value.earthquake),
    issue: EEWAllOfIssueToJSON(value.issue),
    cancelled: value.cancelled,
    areas:
      value.areas === undefined
        ? undefined
        : (value.areas as Array<any>).map(EEWAllOfAreasToJSON),
  };
}
