/* tslint:disable */
/* eslint-disable */
/**
 * P2P地震情報 API仕様書
 * - 商用・非商用問わず無償（無料）でご利用になれます。 [二次利用できます · P2P地震情報](https://www.p2pquake.net/secondary_use/) をご確認ください。 - 以下のレート制限があります。超えるとレスポンスが遅くなったり拒否 (HTTP ステータスコード 429) される場合があります。   - /history: 60 リクエスト/分 (IP アドレス毎)   - /jma: 10 リクエスト/分 (IP アドレス毎)
 *
 * The version of the OpenAPI document: 2.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "./runtime";
import type { BasicData } from "./BasicData";
import {
  BasicDataFromJSON,
  BasicDataFromJSONTyped,
  BasicDataToJSON,
} from "./BasicData";
import type { EEWDetectionAllOf } from "./EEWDetectionAllOf";
import {
  EEWDetectionAllOfFromJSON,
  EEWDetectionAllOfFromJSONTyped,
  EEWDetectionAllOfToJSON,
} from "./EEWDetectionAllOf";

/**
 *
 * @export
 * @interface EEWDetection
 */
export interface EEWDetection {
  /**
   * 情報を一意に識別するID
   * @type {string}
   * @memberof EEWDetection
   */
  id: string;
  /**
   * 情報コード。常に554です。
   * @type {any}
   * @memberof EEWDetection
   */
  code: any | null;
  /**
   * 受信日時。形式は `2006/01/02 15:04:05.999` です。
   * @type {string}
   * @memberof EEWDetection
   */
  time: string;
  /**
   * 検出種類
   * @type {string}
   * @memberof EEWDetection
   */
  type: EEWDetectionTypeEnum;
}

/**
 * @export
 */
export const EEWDetectionTypeEnum = {
  Full: "Full (チャイム＋音声)",
  Chime: "Chime (チャイム (未実装))",
} as const;
export type EEWDetectionTypeEnum =
  typeof EEWDetectionTypeEnum[keyof typeof EEWDetectionTypeEnum];

/**
 * Check if a given object implements the EEWDetection interface.
 */
export function instanceOfEEWDetection(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "code" in value;
  isInstance = isInstance && "time" in value;
  isInstance = isInstance && "type" in value;

  return isInstance;
}

export function EEWDetectionFromJSON(json: any): EEWDetection {
  return EEWDetectionFromJSONTyped(json, false);
}

export function EEWDetectionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EEWDetection {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    code: json["code"],
    time: json["time"],
    type: json["type"],
  };
}

export function EEWDetectionToJSON(value?: EEWDetection | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    code: value.code,
    time: value.time,
    type: value.type,
  };
}
