/* tslint:disable */
/* eslint-disable */
/**
 * P2P地震情報 API仕様書
 * - 商用・非商用問わず無償（無料）でご利用になれます。 [二次利用できます · P2P地震情報](https://www.p2pquake.net/secondary_use/) をご確認ください。 - 以下のレート制限があります。超えるとレスポンスが遅くなったり拒否 (HTTP ステータスコード 429) される場合があります。   - /history: 60 リクエスト/分 (IP アドレス毎)   - /jma: 10 リクエスト/分 (IP アドレス毎)
 *
 * The version of the OpenAPI document: 2.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "./runtime";
/**
 * 発表元の情報
 * @export
 * @interface JMAQuakeAllOfIssue
 */
export interface JMAQuakeAllOfIssue {
  /**
   * 発表元
   * @type {string}
   * @memberof JMAQuakeAllOfIssue
   */
  source?: string;
  /**
   * 発表日時
   * @type {string}
   * @memberof JMAQuakeAllOfIssue
   */
  time: string;
  /**
   * 発表種類
   * @type {string}
   * @memberof JMAQuakeAllOfIssue
   */
  type: JMAQuakeAllOfIssueTypeEnum;
  /**
   * 訂正の有無
   * @type {string}
   * @memberof JMAQuakeAllOfIssue
   */
  correct?: JMAQuakeAllOfIssueCorrectEnum;
}

/**
 * @export
 */
export const JMAQuakeAllOfIssueTypeEnum = {
  ScalePrompt: "ScalePrompt(震度速報)",
  Destination: "Destination(震源に関する情報)",
  ScaleAndDestination: "ScaleAndDestination(震度・震源に関する情報)",
  DetailScale: "DetailScale(各地の震度に関する情報)",
  Foreign: "Foreign(遠地地震に関する情報)",
  Other: "Other(その他の情報)",
} as const;
export type JMAQuakeAllOfIssueTypeEnum =
  typeof JMAQuakeAllOfIssueTypeEnum[keyof typeof JMAQuakeAllOfIssueTypeEnum];

/**
 * @export
 */
export const JMAQuakeAllOfIssueCorrectEnum = {
  None: "None(なし)",
  Unknown: "Unknown(不明)",
  ScaleOnly: "ScaleOnly(震度)",
  DestinationOnly: "DestinationOnly(震源)",
  ScaleAndDestination: "ScaleAndDestination(震度・震源)",
} as const;
export type JMAQuakeAllOfIssueCorrectEnum =
  typeof JMAQuakeAllOfIssueCorrectEnum[keyof typeof JMAQuakeAllOfIssueCorrectEnum];

/**
 * Check if a given object implements the JMAQuakeAllOfIssue interface.
 */
export function instanceOfJMAQuakeAllOfIssue(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "time" in value;
  isInstance = isInstance && "type" in value;

  return isInstance;
}

export function JMAQuakeAllOfIssueFromJSON(json: any): JMAQuakeAllOfIssue {
  return JMAQuakeAllOfIssueFromJSONTyped(json, false);
}

export function JMAQuakeAllOfIssueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): JMAQuakeAllOfIssue {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    source: !exists(json, "source") ? undefined : json["source"],
    time: json["time"],
    type: json["type"],
    correct: !exists(json, "correct") ? undefined : json["correct"],
  };
}

export function JMAQuakeAllOfIssueToJSON(
  value?: JMAQuakeAllOfIssue | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    source: value.source,
    time: value.time,
    type: value.type,
    correct: value.correct,
  };
}
