/* tslint:disable */
/* eslint-disable */
/**
 * P2P地震情報 API仕様書
 * - 商用・非商用問わず無償（無料）でご利用になれます。 [二次利用できます · P2P地震情報](https://www.p2pquake.net/secondary_use/) をご確認ください。 - 以下のレート制限があります。超えるとレスポンスが遅くなったり拒否 (HTTP ステータスコード 429) される場合があります。   - /history: 60 リクエスト/分 (IP アドレス毎)   - /jma: 10 リクエスト/分 (IP アドレス毎)
 *
 * The version of the OpenAPI document: 2.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "./runtime";
import type { BasicData } from "./BasicData";
import {
  BasicDataFromJSON,
  BasicDataFromJSONTyped,
  BasicDataToJSON,
} from "./BasicData";
import type { JMATsunamiAllOf } from "./JMATsunamiAllOf";
import {
  JMATsunamiAllOfFromJSON,
  JMATsunamiAllOfFromJSONTyped,
  JMATsunamiAllOfToJSON,
} from "./JMATsunamiAllOf";
import type { JMATsunamiAllOfAreas } from "./JMATsunamiAllOfAreas";
import {
  JMATsunamiAllOfAreasFromJSON,
  JMATsunamiAllOfAreasFromJSONTyped,
  JMATsunamiAllOfAreasToJSON,
} from "./JMATsunamiAllOfAreas";
import type { JMATsunamiAllOfIssue } from "./JMATsunamiAllOfIssue";
import {
  JMATsunamiAllOfIssueFromJSON,
  JMATsunamiAllOfIssueFromJSONTyped,
  JMATsunamiAllOfIssueToJSON,
} from "./JMATsunamiAllOfIssue";

/**
 *
 * @export
 * @interface JMATsunami
 */
export interface JMATsunami {
  /**
   * 情報を一意に識別するID
   * @type {string}
   * @memberof JMATsunami
   */
  id: string;
  /**
   * 情報コード。常に552です。
   * @type {any}
   * @memberof JMATsunami
   */
  code: any | null;
  /**
   * 受信日時。形式は `2006/01/02 15:04:05.999` です。
   * @type {string}
   * @memberof JMATsunami
   */
  time: string;
  /**
   * 津波予報が解除されたかどうか。trueの場合、areasは空配列です。
   * @type {boolean}
   * @memberof JMATsunami
   */
  cancelled: boolean;
  /**
   *
   * @type {JMATsunamiAllOfIssue}
   * @memberof JMATsunami
   */
  issue: JMATsunamiAllOfIssue;
  /**
   * 津波予報の詳細
   * @type {Array<JMATsunamiAllOfAreas>}
   * @memberof JMATsunami
   */
  areas?: Array<JMATsunamiAllOfAreas>;
}

/**
 * Check if a given object implements the JMATsunami interface.
 */
export function instanceOfJMATsunami(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "code" in value;
  isInstance = isInstance && "time" in value;
  isInstance = isInstance && "cancelled" in value;
  isInstance = isInstance && "issue" in value;

  return isInstance;
}

export function JMATsunamiFromJSON(json: any): JMATsunami {
  return JMATsunamiFromJSONTyped(json, false);
}

export function JMATsunamiFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): JMATsunami {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    code: json["code"],
    time: json["time"],
    cancelled: json["cancelled"],
    issue: JMATsunamiAllOfIssueFromJSON(json["issue"]),
    areas: !exists(json, "areas")
      ? undefined
      : (json["areas"] as Array<any>).map(JMATsunamiAllOfAreasFromJSON),
  };
}

export function JMATsunamiToJSON(value?: JMATsunami | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    code: value.code,
    time: value.time,
    cancelled: value.cancelled,
    issue: JMATsunamiAllOfIssueToJSON(value.issue),
    areas:
      value.areas === undefined
        ? undefined
        : (value.areas as Array<any>).map(JMATsunamiAllOfAreasToJSON),
  };
}
