/* tslint:disable */
/* eslint-disable */
/**
 * P2P地震情報 API仕様書
 * - 商用・非商用問わず無償（無料）でご利用になれます。 [二次利用できます · P2P地震情報](https://www.p2pquake.net/secondary_use/) をご確認ください。 - 以下のレート制限があります。超えるとレスポンスが遅くなったり拒否 (HTTP ステータスコード 429) される場合があります。   - /history: 60 リクエスト/分 (IP アドレス毎)   - /jma: 10 リクエスト/分 (IP アドレス毎)
 *
 * The version of the OpenAPI document: 2.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "./runtime";
/**
 * 地震感知情報
 * @export
 * @interface UserquakeAllOf
 */
export interface UserquakeAllOf {
  /**
   * 情報コード。常に561です。
   * @type {any}
   * @memberof UserquakeAllOf
   */
  code?: any | null;
  /**
   * 地域コード（コード一覧は [GitHub: epsp-specifications/epsp-area.csv · p2pquake/epsp-specifications](https://github.com/p2pquake/epsp-specifications/blob/master/epsp-area.csv) 参照）
   * @type {number}
   * @memberof UserquakeAllOf
   */
  area: number;
}

/**
 * Check if a given object implements the UserquakeAllOf interface.
 */
export function instanceOfUserquakeAllOf(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "area" in value;

  return isInstance;
}

export function UserquakeAllOfFromJSON(json: any): UserquakeAllOf {
  return UserquakeAllOfFromJSONTyped(json, false);
}

export function UserquakeAllOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserquakeAllOf {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    code: !exists(json, "code") ? undefined : json["code"],
    area: json["area"],
  };
}

export function UserquakeAllOfToJSON(value?: UserquakeAllOf | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    code: value.code,
    area: value.area,
  };
}
